"""init tables

Revision ID: d3721b4507b4
Revises: 
Create Date: 2023-11-02 01:09:00.086369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3721b4507b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_name',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('site_name_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('site_name_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_name_id', sa.INTEGER(), nullable=True),
    sa.Column('header', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_prescription', sa.BOOLEAN(), nullable=False),
    sa.Column('img_src', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['site_name_id'], ['site_name.site_name_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('header')
    )
    op.create_table('price',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('price_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('product')
    op.drop_table('site_name')
    # ### end Alembic commands ###
