"""init base table

Revision ID: e63d8915cde1
Revises: 
Create Date: 2023-10-18 12:04:44.703764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63d8915cde1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('header', sa.VARCHAR(length=255), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=2), nullable=False),
    sa.Column('is_prescription', sa.BOOLEAN(), nullable=False),
    sa.Column('img_src', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
