"""add_field

Revision ID: ff165611a5d1
Revises: b7f67e834993
Create Date: 2023-11-04 22:50:45.418127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff165611a5d1'
down_revision = 'b7f67e834993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('link', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'link')
    # ### end Alembic commands ###
